### ISSUE TITLE
Only works with some SVG when have many in one folder

### ISSUE THREAD

**Issue by 4colors-ogawa-ken** [AngusJohnson/SvgShellExtensions#5]
I have a folder with 20 or more SVG files, it only previews the first 5 or 10...
I'm using Windows 11

**Comment by AngusJohnson** [comment]
I'm using **SvgShellExtensions** in Windows 11 without problems, and some folders have well over 50 SVG images.
Perhaps there's an issue with specific images rather than the number of images. Have you tried copying several of the images that aren't being displayed into a seperate folder and seeing the images are being rendered there?
